name: ReadiumOPDS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    env:
      scheme: ${{ 'r2-opds-swift' }}
      platform: ${{ 'iOS Simulator' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install xcodegen
      - name: Check Carthage project
        run: |
          # Check that the Carthage project is up to date.
          make carthage
          git diff --exit-code --name-only readium-opds.xcodeproj
      - name: Prepare build
        run: |
          # readium-opds.xcodeproj is only relevant for Carthage. We remove it otherwise xcodebuild will use it.
          rm -rf readium-opds.xcodeproj
      - name: Build
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=$device"
